### DISCUSSION TITLE
🐰 혹시… 쓸쓸한 싸움을 하고 계시진 않으신지..? feat.코드리뷰AI

### DISCUSSION THREAD

**Discussion by bisor0627** [DeveloperAcademy-POSTECH/.github#114] [Idea]
> 나 혼자 코드를 짜며 머릿속에서 수백 번 “이게 최선인가?“를 되뇌었다면,  
> 이제는 짱 귀여운 코드리뷰 요정(CodeRabbit)의 힘을 빌려보시는 것도…? 🐰✨

## ✅ 도입 배경

- C2 개인 프로젝트 중이라 리뷰 피드백 루프가 힘들었음
- 코드리뷰 요청하기 조금 수줍음
- PR을 만들고도 “이게 Swift에서 적절한 코드인가…?” 하는 막연한 불안감이 있었음
- SwiftLint 기반의 스타일 가이드를 유지하며 리뷰를 받고 싶었음
- ~~원래 신기한 거 써보기를 좋아함~~
- [이 글](https://tech.inflab.com/20250303-introduce-coderabbit/)을 읽어버림

## 🛠️ Step 1. CodeRabbit 가입 및 설치

1. [CodeRabbit 공식 빠른 시작 가이드](https://docs.coderabbit.ai/getting-started/quickstart)
2. GitHub 계정으로 로그인
3. 연동할 저장소 선택 (전체 선택 추천)
4. `.coderabbit.yaml` 파일을 Git 루트에 생성
5. [CodeRabbit 설정 문서](https://docs.coderabbit.ai/getting-started/configure-coderabbit) 참고

## ⚙️ Step 2. `.coderabbit.yaml` 설정 (Swift 기준)

```yaml
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko"  # 리뷰 언어는 한국어로 설정
early_access: false

reviews:
  profile: "assertive"
  auto_review:
    enabled: true
    drafts: false

  tools:
    swiftlint:
      enabled: true
      config_file: "path/your/.swiftlint.yml" #.swiftlint.yml이 있을 경우에, .coderabbit.yaml기준 상대경로로 작성하면 됩니다.
    yamllint:
      enabled: true
    languagetool:
      enabled: true
      level: picky

chat:
  auto_reply: true
```

✅ 참고:
- `reviews.tools.swiftlint.config_file` 키를 통해 `.swiftlint.yml`이 루트가 아니어도 정상 작동합니다.  
- Swift는 `conventions` 항목을 사용하지 않고, 대신 `tools.swiftlint`로 스타일 가이드를 정의합니다.
> 참고로 `conventions` JavaScript 생태계 중심으로 사용되는 옵션입니다.
> 예:
```yaml
conventions:
  - typescript
  - react
  - eslint
  - next.js
```
→ Swift 프로젝트에서는 사용하지 않아도 됩니다.

## 🧪 Step 3. SwiftLint 연동 (`path/your/.swiftlint.yml`)

```yaml
included:
  - <ProjectName>

excluded:
  - Pods
  - <ProjectName>Tests

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - trailing_closure
  - unused_import

custom_rules:
  no_get_prefix:
    name: "'get' 접두사 지양"
    regex: "func\\s+get[A-Z]"
    message: "데이터를 가져오는 함수의 경우 `get` 접두사는 지양해주세요."
    severity: warning
   .
   .
   .
   # 팀 규격에 맞는 여러 lint 설정들...
```

👉 [SwiftLint Rules 설명](https://realm.github.io/SwiftLint/rule-directory.html)
👉 [Apple Developer Academy 스타일 가이드](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide)

### 문제 상황

💥 **Validation error**: Unrecognized key(s) in object: 'review'  
**▶️ 해결**: `review` → `reviews`로 수정하세요.

🐰 그리고 이런 실수는 CodeRabbit이 직접 PR 코멘트로 친절하게 알려줍니다!

> ❌ `Unrecognized key(s) in object: 'review'`  
> 👉 Did you mean `reviews` instead? Please check the documentation.

자동화된 리뷰 요정이 사용 방법까지 친절하게 알려줍니다...☘️

### 자동 리뷰가 안 되는 대표 상황

> Auto reviews are disabled on base/target branches other than the default branch.

**▶️ 해결 방법:**

- 현재는 default 브랜치가 아닌 경우 자동 리뷰를 받는 설정은 지원되지 않으며,
- 수동으로 PR 코멘트에 `@coderabbitai review`를 작성하면 리뷰를 받을 수 있습니다.

## ✨ 실사용 예시

<img width="827" alt="스크린샷 2025-04-18 오전 10 33 55" src="https://github.com/user-attachments/assets/2d1c7c01-00e2-435e-ae3f-da0204d0e479" />

📝 저를 위한 시도 써주고 (yaml 옵션으로 disable 가능)

<img width="748" alt="스크린샷 2025-04-18 오전 10 34 49" src="https://github.com/user-attachments/assets/bcabf4a1-81b6-4aaf-b48d-a84b4bba317a" />

🗣️ 티키타카도 해줍니다.

더 잘 쓰는 방법이 궁금하다면...👉[CodeRabbit의 AI 리뷰 예제](https://github.com/tyaga001/devtoolsacademy/pull/44)

## 💰 가격 정책 (2025년 4월 기준)

| 플랜       | 가격                       | 주요 기능 요약 |
|------------|----------------------------|----------------|
| **Free**   | 무료                       | 무제한 공개/비공개 리포지토리, PR 요약, 14일 Pro 체험 |
| **Lite**   | $12/월/개발자 (연간)<br>$15/월/개발자 (월간) | 무제한 리뷰, 라인별 피드백, 채팅, 실시간 웹 검색, 코드 그래프 분석 |
| **Pro**    | $24/월/개발자 (연간)<br>$30/월/개발자 (월간) | Lite 포함 + Linter/SAST 통합, Jira 연동, 대시보드, 문서화 자동화 |
| **Enterprise** | 맞춤형 견적 | SLA, 다중 조직, 자체 호스팅, 고객 성공 매니저 등 |

## 📌 개인적인 사용 후기는...

- 혼자 개발할 때도 외롭지 않다
- 새벽에도 코드리뷰를 받을 수 있다
- 귀엽다... 진짜 귀엽다...🐰
- SwiftLint와 함께 쓰면 스타일 가이드 준수 + 리뷰 피드백을 동시에 만족시킬 수 있다
- PR을 그냥 넘기지 않고, 진짜 **리뷰 받는 느낌**이라 감동...😭

## 🫶 공유하는 이유

- 코드리뷰를 받고 싶고, 하고 싶은 러너들이 많지만 내 코드를 보여주고 피드백을 받는 게 처음엔 분명 낯설것 같았습니다.
- CodeRabbit은 어느정도 유료 구독이 필요한 서비스이므로, **처음에는 무료 체험**으로 코드리뷰의 긍정적인 면을 느껴보고
**러너들끼리 서로 리뷰를 해주는 흐름**으로 전환해도 좋지 않을까 하는 마음에 공유해봅니다.
- 누군가의 눈으로 리뷰받는 경험은 너무 유익하기에 리뷰를 받고 싶은 사람도, 
코드리뷰를 더 잘해보고 싶은 사람도 경험해보면 너무 좋을 툴이라고 생각합니다.

**당신의 싸움이 쓸쓸하지 않기를**  
🐰 코드리뷰 요정 모셔보세요 🧚🫧
